name: Cypress Regression Tests

on: [push]

jobs:

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          wait-on: ${{ secrets.BASE_URL }}
          project: Cypress/cypress-discovery/buger-eats
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: 'UI - Chrome'
          spec: Cypress/cypress-discovery/buger-eats/cypress/integration/*
          config-file: Cypress/cypress-discovery/buger-eats/package.json
